{"name": "test_open_about", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"dd3a9f14f36c25d158c69271060aa05b\")>\n\n    @allure.description(\"test_open_about\")\n    def test_open_about(driver):\n        log = LoginPage(driver)\n        log.autorization()\n        mp = MainPage(driver)\n        mp.check()\n>       mp.selectMenuAbout()\n\ntests\\test_open_about.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\mainPage.py:71: in selectMenuAbout\n    self.clickAboutPage()\npages\\mainPage.py:56: in clickAboutPage\n    self.getLinkAbout().click()\npages\\mainPage.py:37: in getLinkAbout\n    return WebDriverWait(self.driver, 30).until(EC.element_to_be_clickable((By.XPATH, self.linkAbout)))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"dd3a9f14f36c25d158c69271060aa05b\")>\nmethod = <selenium.webdriver.support.expected_conditions.element_to_be_clickable object at 0x000001FBE5242FD0>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "description": "test_open_about", "steps": [{"name": "autorization", "status": "passed", "start": 1680725194956, "stop": 1680725197689}, {"name": "check", "status": "passed", "start": 1680725197689, "stop": 1680725197776}], "attachments": [{"name": "stdout", "source": "70432fdd-d8a6-4286-a13d-bd01b9ca0355-attachment.txt", "type": "text/plain"}], "start": 1680725194956, "stop": 1680725229465, "uuid": "6e475841-65d1-4406-afae-e76fe1622398", "historyId": "33ce6c50b62156342adae983e3e1c18c", "testCaseId": "045d8929b692b41884b3edb777820813", "fullName": "tests.test_open_about#test_open_about", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_open_about"}, {"name": "host", "value": "LAPTOP-70OVIOCN"}, {"name": "thread", "value": "14776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_open_about"}]}